### ISSUE TITLE
Renew issued certificate

### ISSUE THREAD

**Issue by xrodriguezd** [wushilin/minica#1]
First of all congratulations, I think it's a great project.
I miss a feature that I hope you can implement. It is about renewing a certificate generated by the application.
I don't know if you could implement this feature.
Thanks in advance.

**Comment by wushilin** [comment]
sure, thanks for asking. I will look into this. it should be quite straight forward to do it.

**Comment by wushilin** [comment]
The renew function had been added. 

You can now do this using RESTful API:

```bash
POST /ca/<ca-id>/cert/<cert-id>/<days>
Authorization: xxx

---
Requires admin role
```

Alternatively, admin UI is provided too.

![image](https://github.com/wushilin/minica/assets/7019828/b96ed073-76b1-4609-bc31-7c3915398827)
