### ISSUE TITLE
Keystore are generated without a password

### ISSUE THREAD

**Issue by xrodriguezd** [wushilin/minica#2]
The tool generates a text file with the password, the keystore can be opened with the password in the text file and can also be opened without entering a password.
If a wrong password is entered, the keystore cannot be opened.
Same issue with Trust Store. 
PKCS12 format is generated correctly.

Tested with _KeyStore Explorer 5.5.2_.

**Comment by wushilin** [comment]
Hi Xrodriguezd, not sure if this is still an issue. I think you have closed it, maybe it is a false alarm?
